/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * User Manual available at https://docs.gradle.org/5.4.1/userguide/tutorial_java_projects.html
 */

plugins {
    // Apply the java plugin to add support for Java
    java

    // Apply the application plugin to add support for building an application
    application
}

repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    // Guava (Java用便利ライブラリ集)
    compile("com.google.guava:guava:28.1-jre")
    // JOGL dependencies
    compile("org.jogamp.gluegen:gluegen-rt:2.3.1")
    compile("org.jogamp.jogl:jogl-all:2.3.1")
    // JOGL runtimes
    runtime("org.jogamp.gluegen:gluegen-rt:2.3.1:natives-android-aarch64")
    runtime("org.jogamp.gluegen:gluegen-rt:2.3.1:natives-android-armv6")
    runtime("org.jogamp.gluegen:gluegen-rt:2.3.1:natives-linux-amd64")
    runtime("org.jogamp.gluegen:gluegen-rt:2.3.1:natives-linux-armv6")
    runtime("org.jogamp.gluegen:gluegen-rt:2.3.1:natives-linux-armv6hf")
    runtime("org.jogamp.gluegen:gluegen-rt:2.3.1:natives-linux-i586")
    runtime("org.jogamp.gluegen:gluegen-rt:2.3.1:natives-macosx-universal")
    runtime("org.jogamp.gluegen:gluegen-rt:2.3.1:natives-solaris-amd64")
    runtime("org.jogamp.gluegen:gluegen-rt:2.3.1:natives-solaris-i586")
    runtime("org.jogamp.gluegen:gluegen-rt:2.3.1:natives-windows-amd64")
    runtime("org.jogamp.gluegen:gluegen-rt:2.3.1:natives-windows-i586")

    runtime("org.jogamp.jogl:jogl-all:2.3.1:natives-android-aarch64")
    runtime("org.jogamp.jogl:jogl-all:2.3.1:natives-android-armv6")
    runtime("org.jogamp.jogl:jogl-all:2.3.1:natives-linux-amd64")
    runtime("org.jogamp.jogl:jogl-all:2.3.1:natives-linux-armv6")
    runtime("org.jogamp.jogl:jogl-all:2.3.1:natives-linux-armv6hf")
    runtime("org.jogamp.jogl:jogl-all:2.3.1:natives-linux-i586")
    runtime("org.jogamp.jogl:jogl-all:2.3.1:natives-macosx-universal")
    runtime("org.jogamp.jogl:jogl-all:2.3.1:natives-solaris-amd64")
    runtime("org.jogamp.jogl:jogl-all:2.3.1:natives-solaris-i586")
    runtime("org.jogamp.jogl:jogl-all:2.3.1:natives-windows-amd64")
    runtime("org.jogamp.jogl:jogl-all:2.3.1:natives-windows-i586")
}

application {
    // Define the main class for the application
    mainClassName = "opengl.lecture.App"
}
