/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package opengl.lecture;

import com.jogamp.newt.opengl.GLWindow;
import com.jogamp.opengl.GLCapabilities;
import com.jogamp.opengl.GLProfile;
import com.jogamp.opengl.util.FPSAnimator;

public class App {
    public static void main(String[] args) {
        GLProfile profile = GLProfile.getMaxProgrammable(true);
        GLCapabilities capability = new GLCapabilities(profile);
        GLWindow window = GLWindow.create(capability);
        FPSAnimator animator = new FPSAnimator(60);
        animator.add(window);
        window.setSize(1024,1024);
        window.addGLEventListener(new GLEventHandler());
        window.setVisible(true);
        animator.start();
    }
}
